/**
 * generated by Xtext
 */
package org.sqlproc.model.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.sqlproc.model.processorModel.Artifacts;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class ProcessorModelLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public ProcessorModelLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String text(final Artifacts ele) {
    return "MODEL";
  }
}
