/**
 * generated by Xtext
 */
package org.sqlproc.model.formatting;

import com.google.inject.Inject;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.eclipse.xtext.xbase.annotations.services.XbaseWithAnnotationsGrammarAccess;
import org.eclipse.xtext.xbase.formatting.XbaseFormatter;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.services.XtypeGrammarAccess;
import org.sqlproc.model.services.ProcessorModelGrammarAccess;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
@SuppressWarnings("all")
public class ProcessorModelFormatter extends XbaseFormatter {
  @Inject
  @Extension
  private ProcessorModelGrammarAccess _processorModelGrammarAccess;
  
  protected void configureFormatting(final FormattingConfig c) {
    c.setAutoLinewrap(120);
    FormattingConfig.LinewrapLocator _setLinewrap = c.setLinewrap(0, 1, 2);
    TerminalRule _sL_COMMENTRule = this._processorModelGrammarAccess.getSL_COMMENTRule();
    _setLinewrap.before(_sL_COMMENTRule);
    FormattingConfig.LinewrapLocator _setLinewrap_1 = c.setLinewrap(0, 1, 2);
    TerminalRule _mL_COMMENTRule = this._processorModelGrammarAccess.getML_COMMENTRule();
    _setLinewrap_1.before(_mL_COMMENTRule);
    FormattingConfig.LinewrapLocator _setLinewrap_2 = c.setLinewrap(0, 1, 1);
    TerminalRule _mL_COMMENTRule_1 = this._processorModelGrammarAccess.getML_COMMENTRule();
    _setLinewrap_2.after(_mL_COMMENTRule_1);
    FormattingConfig.LinewrapLocator _setLinewrap_3 = c.setLinewrap(2);
    ProcessorModelGrammarAccess.PackageElements _packageAccess = this._processorModelGrammarAccess.getPackageAccess();
    Keyword _leftCurlyBracketKeyword_2 = _packageAccess.getLeftCurlyBracketKeyword_2();
    _setLinewrap_3.after(_leftCurlyBracketKeyword_2);
    FormattingConfig.LinewrapLocator _setLinewrap_4 = c.setLinewrap();
    ProcessorModelGrammarAccess.PackageElements _packageAccess_1 = this._processorModelGrammarAccess.getPackageAccess();
    Keyword _rightCurlyBracketKeyword_5 = _packageAccess_1.getRightCurlyBracketKeyword_5();
    _setLinewrap_4.before(_rightCurlyBracketKeyword_5);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement = c.setIndentationIncrement();
    ProcessorModelGrammarAccess.PackageElements _packageAccess_2 = this._processorModelGrammarAccess.getPackageAccess();
    Keyword _leftCurlyBracketKeyword_2_1 = _packageAccess_2.getLeftCurlyBracketKeyword_2();
    _setIndentationIncrement.after(_leftCurlyBracketKeyword_2_1);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement = c.setIndentationDecrement();
    ProcessorModelGrammarAccess.PackageElements _packageAccess_3 = this._processorModelGrammarAccess.getPackageAccess();
    Keyword _rightCurlyBracketKeyword_5_1 = _packageAccess_3.getRightCurlyBracketKeyword_5();
    _setIndentationDecrement.before(_rightCurlyBracketKeyword_5_1);
    FormattingConfig.LinewrapLocator _setLinewrap_5 = c.setLinewrap();
    XtypeGrammarAccess.XImportSectionElements _xImportSectionAccess = this._processorModelGrammarAccess.getXImportSectionAccess();
    ParserRule _rule = _xImportSectionAccess.getRule();
    _setLinewrap_5.before(_rule);
    FormattingConfig.LinewrapLocator _setLinewrap_6 = c.setLinewrap();
    ProcessorModelGrammarAccess.ImplementsElements _implementsAccess = this._processorModelGrammarAccess.getImplementsAccess();
    ParserRule _rule_1 = _implementsAccess.getRule();
    _setLinewrap_6.before(_rule_1);
    FormattingConfig.LinewrapLocator _setLinewrap_7 = c.setLinewrap();
    ProcessorModelGrammarAccess.ImplementsElements _implementsAccess_1 = this._processorModelGrammarAccess.getImplementsAccess();
    Keyword _implementsKeyword_1 = _implementsAccess_1.getImplementsKeyword_1();
    _setLinewrap_7.before(_implementsKeyword_1);
    FormattingConfig.LinewrapLocator _setLinewrap_8 = c.setLinewrap();
    ProcessorModelGrammarAccess.ExtendsElements _extendsAccess = this._processorModelGrammarAccess.getExtendsAccess();
    ParserRule _rule_2 = _extendsAccess.getRule();
    _setLinewrap_8.before(_rule_2);
    FormattingConfig.LinewrapLocator _setLinewrap_9 = c.setLinewrap();
    ProcessorModelGrammarAccess.ExtendsElements _extendsAccess_1 = this._processorModelGrammarAccess.getExtendsAccess();
    Keyword _extendsKeyword_1 = _extendsAccess_1.getExtendsKeyword_1();
    _setLinewrap_9.before(_extendsKeyword_1);
    FormattingConfig.LinewrapLocator _setLinewrap_10 = c.setLinewrap(2);
    ProcessorModelGrammarAccess.EnumEntityElements _enumEntityAccess = this._processorModelGrammarAccess.getEnumEntityAccess();
    ParserRule _rule_3 = _enumEntityAccess.getRule();
    _setLinewrap_10.before(_rule_3);
    FormattingConfig.LinewrapLocator _setLinewrap_11 = c.setLinewrap();
    ProcessorModelGrammarAccess.EnumEntityElements _enumEntityAccess_1 = this._processorModelGrammarAccess.getEnumEntityAccess();
    Keyword _enumKeyword_2 = _enumEntityAccess_1.getEnumKeyword_2();
    _setLinewrap_11.before(_enumKeyword_2);
    FormattingConfig.LinewrapLocator _setLinewrap_12 = c.setLinewrap();
    ProcessorModelGrammarAccess.EnumEntityElements _enumEntityAccess_2 = this._processorModelGrammarAccess.getEnumEntityAccess();
    Keyword _leftCurlyBracketKeyword_4 = _enumEntityAccess_2.getLeftCurlyBracketKeyword_4();
    _setLinewrap_12.after(_leftCurlyBracketKeyword_4);
    FormattingConfig.LinewrapLocator _setLinewrap_13 = c.setLinewrap();
    ProcessorModelGrammarAccess.EnumEntityElements _enumEntityAccess_3 = this._processorModelGrammarAccess.getEnumEntityAccess();
    Keyword _rightCurlyBracketKeyword_7 = _enumEntityAccess_3.getRightCurlyBracketKeyword_7();
    _setLinewrap_13.before(_rightCurlyBracketKeyword_7);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_1 = c.setIndentationIncrement();
    ProcessorModelGrammarAccess.EnumEntityElements _enumEntityAccess_4 = this._processorModelGrammarAccess.getEnumEntityAccess();
    Keyword _leftCurlyBracketKeyword_4_1 = _enumEntityAccess_4.getLeftCurlyBracketKeyword_4();
    _setIndentationIncrement_1.after(_leftCurlyBracketKeyword_4_1);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_1 = c.setIndentationDecrement();
    ProcessorModelGrammarAccess.EnumEntityElements _enumEntityAccess_5 = this._processorModelGrammarAccess.getEnumEntityAccess();
    Keyword _rightCurlyBracketKeyword_7_1 = _enumEntityAccess_5.getRightCurlyBracketKeyword_7();
    _setIndentationDecrement_1.before(_rightCurlyBracketKeyword_7_1);
    FormattingConfig.LinewrapLocator _setLinewrap_14 = c.setLinewrap();
    ProcessorModelGrammarAccess.EnumAttributeElements _enumAttributeAccess = this._processorModelGrammarAccess.getEnumAttributeAccess();
    ParserRule _rule_4 = _enumAttributeAccess.getRule();
    _setLinewrap_14.before(_rule_4);
    FormattingConfig.LinewrapLocator _setLinewrap_15 = c.setLinewrap();
    ProcessorModelGrammarAccess.EnumAttributeElements _enumAttributeAccess_1 = this._processorModelGrammarAccess.getEnumAttributeAccess();
    Keyword _attrKeyword_3 = _enumAttributeAccess_1.getAttrKeyword_3();
    _setLinewrap_15.before(_attrKeyword_3);
    FormattingConfig.LinewrapLocator _setLinewrap_16 = c.setLinewrap(2);
    ProcessorModelGrammarAccess.PojoEntityElements _pojoEntityAccess = this._processorModelGrammarAccess.getPojoEntityAccess();
    ParserRule _rule_5 = _pojoEntityAccess.getRule();
    _setLinewrap_16.before(_rule_5);
    FormattingConfig.LinewrapLocator _setLinewrap_17 = c.setLinewrap();
    ProcessorModelGrammarAccess.PojoEntityElements _pojoEntityAccess_1 = this._processorModelGrammarAccess.getPojoEntityAccess();
    Keyword _pojoKeyword_3 = _pojoEntityAccess_1.getPojoKeyword_3();
    _setLinewrap_17.before(_pojoKeyword_3);
    FormattingConfig.LinewrapLocator _setLinewrap_18 = c.setLinewrap();
    ProcessorModelGrammarAccess.PojoEntityElements _pojoEntityAccess_2 = this._processorModelGrammarAccess.getPojoEntityAccess();
    Keyword _leftCurlyBracketKeyword_6 = _pojoEntityAccess_2.getLeftCurlyBracketKeyword_6();
    _setLinewrap_18.after(_leftCurlyBracketKeyword_6);
    FormattingConfig.LinewrapLocator _setLinewrap_19 = c.setLinewrap();
    ProcessorModelGrammarAccess.PojoEntityElements _pojoEntityAccess_3 = this._processorModelGrammarAccess.getPojoEntityAccess();
    Keyword _rightCurlyBracketKeyword_9 = _pojoEntityAccess_3.getRightCurlyBracketKeyword_9();
    _setLinewrap_19.before(_rightCurlyBracketKeyword_9);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_2 = c.setIndentationIncrement();
    ProcessorModelGrammarAccess.PojoEntityElements _pojoEntityAccess_4 = this._processorModelGrammarAccess.getPojoEntityAccess();
    Keyword _leftCurlyBracketKeyword_6_1 = _pojoEntityAccess_4.getLeftCurlyBracketKeyword_6();
    _setIndentationIncrement_2.after(_leftCurlyBracketKeyword_6_1);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_2 = c.setIndentationDecrement();
    ProcessorModelGrammarAccess.PojoEntityElements _pojoEntityAccess_5 = this._processorModelGrammarAccess.getPojoEntityAccess();
    Keyword _rightCurlyBracketKeyword_9_1 = _pojoEntityAccess_5.getRightCurlyBracketKeyword_9();
    _setIndentationDecrement_2.before(_rightCurlyBracketKeyword_9_1);
    FormattingConfig.LinewrapLocator _setLinewrap_20 = c.setLinewrap();
    ProcessorModelGrammarAccess.PojoAttributeElements _pojoAttributeAccess = this._processorModelGrammarAccess.getPojoAttributeAccess();
    ParserRule _rule_6 = _pojoAttributeAccess.getRule();
    _setLinewrap_20.before(_rule_6);
    FormattingConfig.LinewrapLocator _setLinewrap_21 = c.setLinewrap();
    ProcessorModelGrammarAccess.PojoAttributeElements _pojoAttributeAccess_1 = this._processorModelGrammarAccess.getPojoAttributeAccess();
    Keyword _kindAttrKeyword_4_0_0 = _pojoAttributeAccess_1.getKindAttrKeyword_4_0_0();
    _setLinewrap_21.before(_kindAttrKeyword_4_0_0);
    FormattingConfig.LinewrapLocator _setLinewrap_22 = c.setLinewrap();
    ProcessorModelGrammarAccess.PojoAttributeElements _pojoAttributeAccess_2 = this._processorModelGrammarAccess.getPojoAttributeAccess();
    Keyword _kindSimpleKeyword_4_0_1 = _pojoAttributeAccess_2.getKindSimpleKeyword_4_0_1();
    _setLinewrap_22.before(_kindSimpleKeyword_4_0_1);
    FormattingConfig.LinewrapLocator _setLinewrap_23 = c.setLinewrap();
    ProcessorModelGrammarAccess.PojoProcedureElements _pojoProcedureAccess = this._processorModelGrammarAccess.getPojoProcedureAccess();
    Keyword _procKeyword_3 = _pojoProcedureAccess.getProcKeyword_3();
    _setLinewrap_23.before(_procKeyword_3);
    FormattingConfig.LinewrapLocator _setLinewrap_24 = c.setLinewrap(2);
    ProcessorModelGrammarAccess.DaoEntityElements _daoEntityAccess = this._processorModelGrammarAccess.getDaoEntityAccess();
    ParserRule _rule_7 = _daoEntityAccess.getRule();
    _setLinewrap_24.before(_rule_7);
    FormattingConfig.LinewrapLocator _setLinewrap_25 = c.setLinewrap();
    ProcessorModelGrammarAccess.DaoEntityElements _daoEntityAccess_1 = this._processorModelGrammarAccess.getDaoEntityAccess();
    Keyword _daoKeyword_3 = _daoEntityAccess_1.getDaoKeyword_3();
    _setLinewrap_25.before(_daoKeyword_3);
    FormattingConfig.LinewrapLocator _setLinewrap_26 = c.setLinewrap();
    ProcessorModelGrammarAccess.DaoEntityElements _daoEntityAccess_2 = this._processorModelGrammarAccess.getDaoEntityAccess();
    Keyword _leftCurlyBracketKeyword_6_2 = _daoEntityAccess_2.getLeftCurlyBracketKeyword_6();
    _setLinewrap_26.after(_leftCurlyBracketKeyword_6_2);
    FormattingConfig.LinewrapLocator _setLinewrap_27 = c.setLinewrap();
    ProcessorModelGrammarAccess.DaoEntityElements _daoEntityAccess_3 = this._processorModelGrammarAccess.getDaoEntityAccess();
    Keyword _rightCurlyBracketKeyword_9_2 = _daoEntityAccess_3.getRightCurlyBracketKeyword_9();
    _setLinewrap_27.before(_rightCurlyBracketKeyword_9_2);
    FormattingConfig.IndentationLocatorStart _setIndentationIncrement_3 = c.setIndentationIncrement();
    ProcessorModelGrammarAccess.DaoEntityElements _daoEntityAccess_4 = this._processorModelGrammarAccess.getDaoEntityAccess();
    Keyword _leftCurlyBracketKeyword_6_3 = _daoEntityAccess_4.getLeftCurlyBracketKeyword_6();
    _setIndentationIncrement_3.after(_leftCurlyBracketKeyword_6_3);
    FormattingConfig.IndentationLocatorEnd _setIndentationDecrement_3 = c.setIndentationDecrement();
    ProcessorModelGrammarAccess.DaoEntityElements _daoEntityAccess_5 = this._processorModelGrammarAccess.getDaoEntityAccess();
    Keyword _rightCurlyBracketKeyword_9_3 = _daoEntityAccess_5.getRightCurlyBracketKeyword_9();
    _setIndentationDecrement_3.before(_rightCurlyBracketKeyword_9_3);
    FormattingConfig.NoSpaceLocator _setNoSpace = c.setNoSpace();
    TerminalRule _lPARENRule = this._processorModelGrammarAccess.getLPARENRule();
    _setNoSpace.before(_lPARENRule);
    FormattingConfig.NoSpaceLocator _setNoSpace_1 = c.setNoSpace();
    TerminalRule _lPARENRule_1 = this._processorModelGrammarAccess.getLPARENRule();
    _setNoSpace_1.after(_lPARENRule_1);
    FormattingConfig.NoSpaceLocator _setNoSpace_2 = c.setNoSpace();
    TerminalRule _rPARENRule = this._processorModelGrammarAccess.getRPARENRule();
    _setNoSpace_2.before(_rPARENRule);
    FormattingConfig.NoSpaceLocator _setNoSpace_3 = c.setNoSpace();
    TerminalRule _cOMMARule = this._processorModelGrammarAccess.getCOMMARule();
    _setNoSpace_3.before(_cOMMARule);
    FormattingConfig.LinewrapLocator _setLinewrap_28 = c.setLinewrap();
    ProcessorModelGrammarAccess.AnnotationElements _annotationAccess = this._processorModelGrammarAccess.getAnnotationAccess();
    ParserRule _rule_8 = _annotationAccess.getRule();
    _setLinewrap_28.after(_rule_8);
    FormattingConfig.NoSpaceLocator _setNoSpace_4 = c.setNoSpace();
    XbaseWithAnnotationsGrammarAccess.XAnnotationElements _xAnnotationAccess = this._processorModelGrammarAccess.getXAnnotationAccess();
    Keyword _commercialAtKeyword_1 = _xAnnotationAccess.getCommercialAtKeyword_1();
    _setNoSpace_4.after(_commercialAtKeyword_1);
    FormattingConfig.NoSpaceLocator _setNoSpace_5 = c.setNoSpace();
    XbaseWithAnnotationsGrammarAccess.XAnnotationElements _xAnnotationAccess_1 = this._processorModelGrammarAccess.getXAnnotationAccess();
    Keyword _leftParenthesisKeyword_3_0 = _xAnnotationAccess_1.getLeftParenthesisKeyword_3_0();
    _setNoSpace_5.before(_leftParenthesisKeyword_3_0);
    FormattingConfig.NoSpaceLocator _setNoSpace_6 = c.setNoSpace();
    XbaseWithAnnotationsGrammarAccess.XAnnotationElements _xAnnotationAccess_2 = this._processorModelGrammarAccess.getXAnnotationAccess();
    Keyword _leftParenthesisKeyword_3_0_1 = _xAnnotationAccess_2.getLeftParenthesisKeyword_3_0();
    _setNoSpace_6.after(_leftParenthesisKeyword_3_0_1);
    FormattingConfig.NoSpaceLocator _setNoSpace_7 = c.setNoSpace();
    XbaseWithAnnotationsGrammarAccess.XAnnotationElements _xAnnotationAccess_3 = this._processorModelGrammarAccess.getXAnnotationAccess();
    Keyword _rightParenthesisKeyword_3_2 = _xAnnotationAccess_3.getRightParenthesisKeyword_3_2();
    _setNoSpace_7.before(_rightParenthesisKeyword_3_2);
    FormattingConfig.NoSpaceLocator _setNoSpace_8 = c.setNoSpace();
    XbaseWithAnnotationsGrammarAccess.XAnnotationElements _xAnnotationAccess_4 = this._processorModelGrammarAccess.getXAnnotationAccess();
    Keyword _commaKeyword_3_1_0_1_0 = _xAnnotationAccess_4.getCommaKeyword_3_1_0_1_0();
    _setNoSpace_8.before(_commaKeyword_3_1_0_1_0);
  }
}
