/*
 * generated by Xtext
 */
package org.sqlproc.model.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ProcessorModelUiModule extends org.sqlproc.model.ui.AbstractProcessorModelUiModule {
	public ProcessorModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
