/**
 * generated by Xtext
 */
package org.sqlproc.model.scoping;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.sqlproc.model.processorModel.DirectiveProperties;
import org.sqlproc.model.processorModel.PojoAttribute;
import org.sqlproc.model.processorModel.PojoEntity;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class ProcessorDslScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope scope_DirectiveProperties_features(final DirectiveProperties directiveProperties, final EReference eReference) {
    EObject _eContainer = directiveProperties.eContainer();
    EObject _eContainer_1 = _eContainer.eContainer();
    EList<PojoAttribute> _attributes = ((PojoEntity) _eContainer_1).getAttributes();
    return Scopes.scopeFor(_attributes);
  }
}
