/**
 * generated by Xtext
 */
package org.sqlproc.model.validation;

import org.sqlproc.model.validation.AbstractProcessorModelValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ProcessorModelValidator extends AbstractProcessorModelValidator {
}
