/**
 * generated by Xtext
 */
package org.sqlproc.model.ui.contentassist;

import org.sqlproc.model.ui.contentassist.AbstractProcessorModelProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class ProcessorModelProposalProvider extends AbstractProcessorModelProposalProvider {
}
