/*
 * generated by Xtext
 */
package org.sqlproc.model;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProcessorModelRuntimeModule extends org.sqlproc.model.AbstractProcessorModelRuntimeModule {

}
