/**
 * generated by Xtext
 */
package org.sqlproc.model.ui.quickfix;

import org.eclipse.xtext.xbase.annotations.ui.quickfix.XbaseWithAnnotationsQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class ProcessorModelQuickfixProvider extends XbaseWithAnnotationsQuickfixProvider {
}
